export const salesClientFC = [
  {
    label: "Client Name",
    name: "name",
    componentType: "input",
    type: "text",
    placeholder: "Enter Client Name",
  },
  {
    label: "Company Name",
    name: "company",
    componentType: "input",
    type: "text",
    placeholder: "Enter Client Company",
  },
  {
    label: "GST No.",
    name: "GSTIN",
    componentType: "input",
    type: "text",
    placeholder: "Enter GST No",
  },
  {
    label: "TAN No.",
    name: "tanNo",
    componentType: "input",
    type: "text",
    placeholder: "Enter Tax Deduction and Collection Account Number",
  },
  {
    label: "Email Id",
    name: "email",
    componentType: "input",
    type: "text",
    placeholder: "Enter Email",
  },
  {
    label: "Contact No.",
    name: "phone",
    componentType: "input",
    type: "text",
    placeholder: "Enter Contact No",
  },
  {
    label: "Website Url",
    name: "website",
    componentType: "input",
    type: "text",
    placeholder: "Enter Website url",
  },
  {
    label: "Address",
    name: "Address",
    componentType: "input",
    type: "text",
    placeholder: "Enter client address",
  },
  {
    label: "City",
    name: "city",
    componentType: "input",
    type: "text",
    placeholder: "Enter client city",
  },
  {
    label: "State",
    name: "state",
    componentType: "input",
    type: "text",
    placeholder: "Enter client state",
  },
  {
    label: "Pincode",
    name: "pincode",
    componentType: "input",
    type: "text",
    placeholder: "Enter Pincode",
  },
  {
    label: "Country",
    name: "country",
    componentType: "input",
    type: "text",
    placeholder: "Enter country",
  },
  {
    label: "Meeting Date",
    name: "meetingDate",
    componentType: "input",
    type: "date",
  },
  {
    label: "Notes",
    name: "notes",
    componentType: "input",
    type: "text",
    placeholder: "Enter Customer notes",
  },
];