export const seoChecklistTemplate = [
  {
    key: "keyword_research",
    label: "Keyword research completed and approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "keyword_mapping",
    label: "Keywords mapped correctly to relevant pages",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "meta_titles",
    label: "Meta titles written as per SEO length & intent",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "meta_descriptions",
    label: "Meta descriptions optimized for CTR",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "heading_structure",
    label: "H1–H6 structure properly implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "url_structure",
    label: "URLs are short, readable, and keyword-friendly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "internal_linking",
    label: "Internal linking implemented correctly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "image_optimization",
    label: "Images optimized and ALT tags added",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "technical_seo",
    label: "Technical SEO checks completed (indexing, sitemap, robots.txt)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "mobile_usability",
    label: "Mobile usability verified",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "page_speed",
    label: "Page speed checked and optimized",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "structured_data",
    label: "Schema / structured data implemented where required",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "search_console",
    label: "Google Search Console connected",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "analytics",
    label: "Google Analytics connected",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "baseline_report",
    label: "Baseline SEO performance report prepared and shared",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];

export const paidAdsChecklistTemplate = [
  {
    key: "ad_account_access",
    label: "Ad account access verified",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "campaign_objective",
    label: "Campaign objective selected correctly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "location_targeting",
    label: "Location targeting verified (city / region)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "budget_approval",
    label: "Daily & monthly budget approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "audience_targeting",
    label: "Audience targeting defined properly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "negative_keywords",
    label: "Negative keywords / exclusions added",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "ad_copy_review",
    label: "Ad copies reviewed for compliance & clarity",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "creative_guidelines",
    label: "Creatives match brand guidelines",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cta_alignment",
    label: "CTA aligned with campaign goal",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "landing_page_test",
    label: "Lead form / landing page tested",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "conversion_tracking",
    label: "Conversion tracking implemented and tested",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "campaign_structure",
    label: "Campaign structure clean (no overlap)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "campaign_launch",
    label: "Campaign launched successfully",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "initial_performance_check",
    label: "Initial performance checked (impressions, clicks)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "first_report",
    label: "First performance report shared",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];

export const socialMediaChecklistTemplate = [
  {
    key: "profile_bio_optimization",
    label: "Profile bio optimized with keywords",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "profile_branding",
    label: "Profile image & cover aligned with branding",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "contact_cta_update",
    label: "Contact details & CTA button updated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "content_calendar",
    label: "Monthly content calendar prepared",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "content_alignment",
    label: "Content aligned with brand tone & goals",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "creative_approval",
    label: "Creatives approved internally / by client",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "caption_copy",
    label: "Captions written with clear messaging",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "hashtag_optimization",
    label: "Hashtags researched and optimized",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "posting_schedule",
    label: "Posting schedule implemented correctly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "content_consistency",
    label: "Content consistency maintained",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "engagement_monitoring",
    label: "Engagement checked (comments, messages)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "insights_access",
    label: "Insights access verified",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "performance_tracking",
    label: "Performance metrics tracked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "first_report",
    label: "First performance report shared",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "policy_compliance",
    label: "No policy violations or copyright issues",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];

export const webDevelopmentChecklistTemplate = [
  // 🔹 Planning & Architecture
  {
    key: "website_architecture",
    label: "Website architecture finalized",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "seo_friendly_urls",
    label: "SEO-friendly URLs confirmed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "ssr_ssg_strategy",
    label: "SSR / SSG strategy approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "mobile_first_layout",
    label: "Mobile-first layout approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "scope_integrations",
    label: "Scope and integrations locked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Development & Performance
  {
    key: "reusable_components",
    label: "Reusable components implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "image_optimization",
    label: "Images optimized (WebP / AVIF)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "lazy_loading",
    label: "Lazy loading enabled",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "code_minification",
    label: "Code minified and split",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "font_optimization",
    label: "Fonts limited to 2 families",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Security & Code Quality
  {
    key: "ssl_implementation",
    label: "SSL implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "xss_sql_protection",
    label: "XSS & SQL injection protection applied",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "env_variables_secured",
    label: "Environment variables secured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "unused_code_removed",
    label: "Unused code removed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "dev_staging_prod",
    label: "Dev / Staging / Prod separated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];

export const profileFormControl = [
  {
    label: "Name",
    name: "name",
    componentType: "input",
    type: "text",
    placeholder: "Enter Your Name",
  },
  {
    label: "Phone",
    name: "phone",
    componentType: "input",
    type: "tel",
    placeholder: "Enter Your Phone",
  },
  {
    label: "Address",
    name: "address",
    componentType: "textarea",
    type: "text",
  },
  {
    label: "Email",
    name: "email",
    componentType: "input",
    type: "email",
  },
  {
    label: "Date of Birth",
    name: "dob",
    componentType: "input",
    type: "date",
  },
  {
    label: "Gender",
    name: "gender",
    componentType: "select",
    options: [
      { id: "MALE", label: "Male" },
      { id: "FEMALE", label: "Female" },
    ],
  },
];

export const checkFormControl = [
  {
    label: "Key",
    name: "key",
    componentType: "input",
    type: "text",
    placeholder: "Enter Your Key",
  },
  {
    label: "Label",
    name: "label",
    componentType: "input",
    type: "text",
    placeholder: "Enter Your Label",
  },
  {
    label: "Remarks",
    name: "remarks",
    componentType: "input",
    type: "text",
    placeholder: "Enter Your remarks",
  },
  {
    label: "Proof Url",
    name: "proofUrl",
    componentType: "input",
    type: "text",
    placeholder: "Enter Your proofUrl",
  },
];

export const announcementFormControls = [
  {
    name: "title",
    label: "Announcement Title",
    componentType: "input",
    type: "text",
    placeholder: "Enter announcement title",
  },
  {
    name: "content",
    label: "Announcement Content",
    componentType: "textarea",
    placeholder: "Write announcement details here...",
  },
  {
    name: "targetDepartment",
    label: "Target Department",
    componentType: "select",
    options: [
      { id: "ALL", label: "All Departments" },
      { id: "SEO", label: "SEO" },
      { id: "WEB_DEVELOPER", label: "Web Developer" },
      { id: "SOCIAL_MEDIA", label: "Social Media" },
      { id: "ADS_MANAGER", label: "Ads Manager" },
      { id: "SALES", label: "Sales" },
      { id: "OTHER", label: "Other" },
    ],
  },
  {
    name: "startDate",
    label: "Start Date",
    componentType: "input",
    type: "date",
  },
  {
    name: "endDate",
    label: "End Date",
    componentType: "input",
    type: "date",
  },
];

export const createKeyWordFormControls = [
  // {
  //   name: "website",
  //   label: "Website",
  //   componentType: "input",
  //   type: "text",
  //   placeholder: "Enter Website",
  // },
  {
    name: "keyword",
    label: "Keyword",
    componentType: "input",
    type: "text",
    placeholder: "Enter Keyword",
  },
  {
    name: "type",
    label: "Type",
    componentType: "select",
    options: [
      { id: "primary", label: "Primary" },
      { id: "secondary", label: "Secondary" },
    ],
  },
];

export const updateRankingFormControls = [
  {
    name: "position",
    label: "Position",
    componentType: "input",
    type: "number",
    placeholder: "Enter position of keyword",
  },
  {
    name: "page",
    label: "Page",
    componentType: "input",
    type: "number",
    placeholder: "Enter where Page of keyword ranks",
  },
  {
    name: "date",
    label: "Date",
    componentType: "input",
    type: "date",
    placeholder: "Enter where Page of keyword ranks",
  },
];


export const d2cWebsiteChecklistTemplate = [
  // 🔹 Strategy & Planning
  {
    key: "target_customer_segments",
    label: "Target customer segments and personas defined",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "competitor_benchmarking",
    label: "Competitor D2C sites benchmarked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "product_catalog_structure",
    label: "Product catalog structure and categories mapped",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "sitemap_information_architecture",
    label: "Sitemap and information architecture approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "scope_integrations_locked",
    label: "Scope and integrations locked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Design & UX
  {
    key: "mobile_first_design",
    label: "Mobile-first design implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "design_system",
    label: "Design system / reusable components implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "font_optimization",
    label: "Fonts limited to 2 families",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "product_media",
    label: "High-quality lifestyle and product photography/video",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "branding_consistency",
    label: "Consistent branding across all pages",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "accessibility_review",
    label: "Accessibility (WCAG 2.1 AA) reviewed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Product Pages & Catalog
  {
    key: "multiple_product_images",
    label: "Multiple product images with zoom",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "product_video_360",
    label: "Product video or 360° view available",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "pricing_variants_stock",
    label: "Pricing, variants, and stock status displayed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "size_guide",
    label: "Size guide / specification sheet available",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "product_reviews",
    label: "Star ratings and written reviews displayed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cross_sell",
    label: "Cross-sell / upsell / customers also bought implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "search_filters",
    label: "Search with filters and sorting available",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "wishlist",
    label: "Wishlist / Save for later implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Cart & Checkout
  {
    key: "guest_checkout",
    label: "Guest checkout available",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "minimal_checkout",
    label: "One-page or minimal-step checkout",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "multiple_payment_methods",
    label: "Multiple payment options integrated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "shipping_cost_visibility",
    label: "Shipping cost / free-shipping threshold shown",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "discount_code",
    label: "Discount code functionality available",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cart_abandonment",
    label: "Cart abandonment email/SMS flow configured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "order_notifications",
    label: "Order confirmation & shipping emails automated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Trust & Social Proof
  {
    key: "verified_reviews_platform",
    label: "Verified reviews platform integrated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "ugc_social_feed",
    label: "User-generated content / social feed integrated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "trust_badges",
    label: "Trust badges displayed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "return_policy",
    label: "Return & exchange policy published",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "affiliate_tracking",
    label: "Influencer / affiliate tracking configured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Marketing & Retention
  {
    key: "email_platform",
    label: "Email marketing platform integrated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "automation_flows",
    label: "Abandoned-cart & post-purchase flows live",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "loyalty_program",
    label: "Loyalty / rewards program implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "referral_program",
    label: "Referral program implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "sms_marketing",
    label: "SMS marketing opt-in configured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "subscribe_save",
    label: "Subscribe & save option available",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Technical Performance
  {
    key: "image_optimization",
    label: "Images optimized (WebP / AVIF)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "lazy_loading",
    label: "Lazy loading enabled",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "code_minification",
    label: "Code minified and split",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "unused_code_removed",
    label: "Unused code removed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "core_web_vitals",
    label: "Core Web Vitals passing (LCP, CLS, INP)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cdn_configured",
    label: "CDN configured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 SEO
  {
    key: "product_category_seo",
    label: "Product & category page SEO completed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "schema_markup",
    label: "Schema markup added",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "sitemap_robots",
    label: "XML sitemap & robots.txt submitted",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "content_marketing",
    label: "Content/blog for organic discovery published",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Security & Compliance
  {
    key: "ssl",
    label: "SSL implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "xss_sql_protection",
    label: "XSS & SQL injection protection applied",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "pci_dss",
    label: "PCI DSS compliance ensured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "env_variables",
    label: "Environment variables secured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cookie_consent",
    label: "GDPR/CCPA-compliant cookie consent implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "legal_policies",
    label: "Privacy, Terms, Shipping & Return policies published",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Analytics & Tracking
  {
    key: "ga4_ecommerce",
    label: "GA4 with ecommerce tracking enabled",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "marketing_pixels",
    label: "Meta / TikTok / Pinterest pixels installed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "conversion_tracking",
    label: "Revenue & conversion tracking configured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "ab_testing",
    label: "A/B testing tool configured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 QA & Launch
  {
    key: "environments_separated",
    label: "Dev / Staging / Prod environments separated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cross_browser_testing",
    label: "Cross-browser, cross-device & payment testing completed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "inventory_sync",
    label: "Inventory sync tested",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "tax_currency_validation",
    label: "Tax & currency calculations verified",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "backup_rollback",
    label: "Backup & rollback plan documented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "post_launch_monitoring",
    label: "Post-launch monitoring in place",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];

export const b2bWebsiteChecklistTemplate = [
  // 🔹 Strategy & Planning
  {
    key: "icp_buyer_personas",
    label: "Ideal Customer Profile (ICP) and buyer personas defined",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "buyer_journey_mapping",
    label: "Buyer journey mapped to site structure",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "decision_maker_content",
    label: "Decision-makers identified with dedicated content",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "competitor_benchmarking",
    label: "Competitor websites benchmarked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "sitemap_information_architecture",
    label: "Sitemap and information architecture approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "scope_integrations_locked",
    label: "Scope and integrations locked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Design & UX
  {
    key: "homepage_value_proposition",
    label: "Value proposition clear within 5 seconds on homepage",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "design_system",
    label: "Design system / reusable components implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "font_optimization",
    label: "Fonts limited to 2 families",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "branding_consistency",
    label: "Consistent branding across all pages",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "responsive_design",
    label: "Responsive design tested across desktop, tablet, and mobile",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "accessibility_review",
    label: "Accessibility (WCAG 2.1 AA) reviewed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Content & Trust
  {
    key: "homepage_messaging",
    label: "Homepage clearly explains who you help, how, and why you're different",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "solution_pages",
    label: "Solution pages organized by industry or use case",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "case_studies",
    label: "Case studies with measurable outcomes published",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "client_logos",
    label: "\"Trusted by\" client logo section added",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "third_party_reviews",
    label: "Third-party review platforms linked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "lead_magnets",
    label: "Whitepapers, guides, or eBooks available as lead magnets",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "faq_section",
    label: "FAQ section addressing common objections",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "team_bios",
    label: "Leadership/team bios published",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "resource_hub",
    label: "Blog or resource hub available",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Lead Generation & Sales Enablement
  {
    key: "primary_cta",
    label: "Primary CTA repeated consistently across pages",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "optimized_forms",
    label: "Forms limited to essential fields",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "meeting_scheduler",
    label: "Meeting scheduler integrated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "live_chat",
    label: "Live chat or lead-qualifying chatbot installed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "crm_gated_content",
    label: "Gated content connected to CRM",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "roi_calculator",
    label: "ROI or savings calculator implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "newsletter_subscription",
    label: "Newsletter/resource subscription available",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "demo_flow",
    label: "Free trial or demo request flow tested",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Integrations
  {
    key: "crm_integration",
    label: "CRM connected",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "marketing_automation",
    label: "Marketing automation and nurture sequences live",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "tracking_pixels",
    label: "Advertising and tracking pixels installed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "webinar_platform",
    label: "Webinar or event platform integrated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "developer_portal",
    label: "API documentation or developer portal published",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Technical Performance
  {
    key: "image_optimization",
    label: "Images optimized (WebP / AVIF)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "lazy_loading",
    label: "Lazy loading enabled",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "code_minification",
    label: "Code minified and split",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "unused_code_removed",
    label: "Unused code removed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "core_web_vitals",
    label: "Core Web Vitals passing (LCP, CLS, INP)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cdn_configured",
    label: "CDN configured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 SEO
  {
    key: "keyword_research",
    label: "Keyword research completed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "on_page_seo",
    label: "On-page SEO implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "schema_markup",
    label: "Schema markup added",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "sitemap_robots",
    label: "XML sitemap and robots.txt submitted",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "internal_linking",
    label: "Internal linking strategy implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Security & Compliance
  {
    key: "ssl",
    label: "SSL implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "xss_sql_protection",
    label: "XSS & SQL injection protection applied",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "env_variables",
    label: "Environment variables secured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cookie_consent",
    label: "GDPR/CCPA-compliant cookie consent implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "security_badges",
    label: "SOC 2 / ISO badges displayed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "legal_policies",
    label: "Privacy policy, terms of service, and cookie policy published",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Analytics & Reporting
  {
    key: "ga4_tracking",
    label: "GA4 (or equivalent) configured with goals/events",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "utm_strategy",
    label: "UTM strategy defined for all campaigns",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "mql_sql_tracking",
    label: "MQLs and SQLs tracked back to source",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "shared_dashboard",
    label: "Shared dashboard for sales and marketing teams",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 QA & Launch
  {
    key: "environments_separated",
    label: "Dev / Staging / Prod environments separated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cross_browser_testing",
    label: "Cross-browser and cross-device testing completed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "form_testing",
    label: "Form submissions tested for routing and notifications",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "redirect_mapping",
    label: "404 pages and redirects mapped",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "backup_rollback",
    label: "Backup and rollback plan documented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "post_launch_monitoring",
    label: "Post-launch monitoring in place",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];
