export const seoChecklistTemplate = [
  {
    key: "keyword_research",
    label: "Keyword research completed and approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "keyword_mapping",
    label: "Keywords mapped correctly to relevant pages",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "meta_titles",
    label: "Meta titles written as per SEO length & intent",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "meta_descriptions",
    label: "Meta descriptions optimized for CTR",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "heading_structure",
    label: "H1–H6 structure properly implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "url_structure",
    label: "URLs are short, readable, and keyword-friendly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "internal_linking",
    label: "Internal linking implemented correctly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "image_optimization",
    label: "Images optimized and ALT tags added",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "technical_seo",
    label: "Technical SEO checks completed (indexing, sitemap, robots.txt)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "mobile_usability",
    label: "Mobile usability verified",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "page_speed",
    label: "Page speed checked and optimized",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "structured_data",
    label: "Schema / structured data implemented where required",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "search_console",
    label: "Google Search Console connected",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "analytics",
    label: "Google Analytics connected",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "baseline_report",
    label: "Baseline SEO performance report prepared and shared",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];


export const paidAdsChecklistTemplate = [
  {
    key: "ad_account_access",
    label: "Ad account access verified",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "campaign_objective",
    label: "Campaign objective selected correctly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "location_targeting",
    label: "Location targeting verified (city / region)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "budget_approval",
    label: "Daily & monthly budget approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "audience_targeting",
    label: "Audience targeting defined properly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "negative_keywords",
    label: "Negative keywords / exclusions added",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "ad_copy_review",
    label: "Ad copies reviewed for compliance & clarity",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "creative_guidelines",
    label: "Creatives match brand guidelines",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "cta_alignment",
    label: "CTA aligned with campaign goal",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "landing_page_test",
    label: "Lead form / landing page tested",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "conversion_tracking",
    label: "Conversion tracking implemented and tested",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "campaign_structure",
    label: "Campaign structure clean (no overlap)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "campaign_launch",
    label: "Campaign launched successfully",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "initial_performance_check",
    label: "Initial performance checked (impressions, clicks)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "first_report",
    label: "First performance report shared",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];


export const socialMediaChecklistTemplate = [
  {
    key: "profile_bio_optimization",
    label: "Profile bio optimized with keywords",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "profile_branding",
    label: "Profile image & cover aligned with branding",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "contact_cta_update",
    label: "Contact details & CTA button updated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "content_calendar",
    label: "Monthly content calendar prepared",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "content_alignment",
    label: "Content aligned with brand tone & goals",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "creative_approval",
    label: "Creatives approved internally / by client",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "caption_copy",
    label: "Captions written with clear messaging",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "hashtag_optimization",
    label: "Hashtags researched and optimized",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "posting_schedule",
    label: "Posting schedule implemented correctly",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "content_consistency",
    label: "Content consistency maintained",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "engagement_monitoring",
    label: "Engagement checked (comments, messages)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "insights_access",
    label: "Insights access verified",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "performance_tracking",
    label: "Performance metrics tracked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "first_report",
    label: "First performance report shared",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "policy_compliance",
    label: "No policy violations or copyright issues",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];


export const webDevelopmentChecklistTemplate = [
  // 🔹 Planning & Architecture
  {
    key: "website_architecture",
    label: "Website architecture finalized",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "seo_friendly_urls",
    label: "SEO-friendly URLs confirmed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "ssr_ssg_strategy",
    label: "SSR / SSG strategy approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "mobile_first_layout",
    label: "Mobile-first layout approved",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "scope_integrations",
    label: "Scope and integrations locked",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Development & Performance
  {
    key: "reusable_components",
    label: "Reusable components implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "image_optimization",
    label: "Images optimized (WebP / AVIF)",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "lazy_loading",
    label: "Lazy loading enabled",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "code_minification",
    label: "Code minified and split",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "font_optimization",
    label: "Fonts limited to 2 families",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },

  // 🔹 Security & Code Quality
  {
    key: "ssl_implementation",
    label: "SSL implemented",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "xss_sql_protection",
    label: "XSS & SQL injection protection applied",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "env_variables_secured",
    label: "Environment variables secured",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "unused_code_removed",
    label: "Unused code removed",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
  {
    key: "dev_staging_prod",
    label: "Dev / Staging / Prod separated",
    completed: false,
    completedAt: null,
    remarks: "",
    proofUrl: "",
  },
];
